uis/pom.xml

resolves https://github.com/BiglySoftware/BiglyBT/issues/19
Finally I couldn't manage to do it via maven only so it's via ant inside maven :/
I'm sure someone can improve it to get rid of the ant part :)  (At least we don't need to install ant)

Plugin Api generation via ant inside maven

---

uis/pom.xml

https://github.com/BiglySoftware/BiglyBT/commit/4e313f361849cf6fbc385964e80a2b5ae50844b4

Update Pom: Don't expose UIInstanceBase class to Plugin Interface.

---

uis/pom.xml

The expression ${build.directory} is deprecated. Please use ${project.build.directory} instead.

changed deprecated expression

---

core/src/com/biglybt/pifimpl/update/PluginUpdatePlugin.java

The plugin update checker outputs multiple log lines for each check performed, but those checks are not atomic so their output can be interleaved, leading to confusing output like:
```
[  Downloading: http://plugins.biglybt.com/update/pluginlist3.php]
Checking TimedAutoStart
Checking azupdater
Current: 2.0.0.1_CVS, Latest: 2.0.0.1_CVS
Checking azutp
Current: 2.1_CVS, Latest: 2.1_CVS
Current: 0.6.2_CVS, Latest: 0.6.2_CVS
```
This patch changes the log format so that version-string lines are not assumed to immediately follow the corresponding "Checking" line. Relevant information is included in each line of output.
The above log would instead be formatted:
```
[  Downloading: http://plugins.biglybt.com/update/pluginlist3.php]
Checking TimedAutoStart
Checking azupdater
Plugin: TimedAutoStart …
```

azbppluginupdate: Update log format

---

uis/pom.xml

[INFO] --- maven-shade-plugin:3.0.0:shade (default) @ biglybt-ui ---
[INFO] Including com.biglybt:biglybt-core:jar:1.5.0.1-SNAPSHOT in the shaded jar.
[INFO] Excluding commons-cli:commons-cli:jar:1.4 from the shaded jar.
[INFO] Excluding log4j:log4j:jar:1.2.17 from the shaded jar.
[INFO] No artifact matching filter com.giblybt:biglybt-core
Fix typo in biglybt-core's groupId.

maven-shade-plugin ignores biglybt-core

---

core/src/com/biglybt/pif/PluginState.java
core/src/com/biglybt/pifimpl/local/PluginStateImpl.java

Hi BiglyBT folks!
In auditing Fedora, we discovered that two of the files in the "azureus" package were licensed GPLv2 only, while the rest of the codebase was GPLv2 or later. 
Specifically: 
PluginStateImpl.java
PluginState.java
This is important because azureus (then vuze, and now BiglyBT) makes extensive use of other Java components which are under the Apache 2.0 license. The Apache 2.0 license is compatible with
GPL version 3, but not with GPL version 2. In order to resolve the licensing issue, we need to be able to trigger the "or later" clause.
I reached out to @the-allanc and confirmed that he was the copyright holder for these works. In email (which I am happy to provide copies of, if necessary), he gave permission for those two files to be used under either version 2 of the GPL …

Update Allan Crooks files to be GPLv2 or later

---

uis/src/com/biglybt/ui/swt/TextViewerWindow.java

So, I found a way to solve the `Search For Existing Files...` twitching. It's kind of brute-force, but it works.
I just turned wrapping on for the `TextViewerWindow`. 
(Actually, I turned wrapping on for _all_ `TextViewerWindow` instances, since that option wasn't overrideable from the caller. So, I'm not sure what the side effects of that would be; depends where else `TextViewerWindow` is used.)
Like I said, brute-force. Your call on whether it's the _right_ fix. (And I'm fully anticipating that it isn't, so don't hesitate to reject this PR. But I figured maybe it'll trigger some inspiration for a _right_-er fix.) I wanted to report that it _does_ solve the twitching issue, anyway.
Fixes: #545

Add wrapping to TextViewerWindow (for "...Existing Files")

---

uis/src/com/biglybt/ui/swt/Utils.java

On Linux, the current escaping doesn't work for files/dirs that have spaces.
The only way that works is explicitly passing `xdg-open` separately from the filename (in an array) to `Runtime.exec(String cmdarray)`.
I also got rid of htmlview as a fallback because xdg-open doesn't ever fail unless it isn't installed. It also opens URLs.
I should note that there's another way of getting xdg-open to work: to URLEncode the filename. This was more problematic as it required making assumptions about what is being opened (if it is already a URL or already encoded, then it would be double-encoded). The current solution seems to work for URLs and files and directories and is the least complex.

Fix launching files that contain spaces on Linux

---

core/src.test/com/biglybt/core/internat/MessageTextTest.java
core/src/com/biglybt/core/internat/MessageText.java
core/src/com/biglybt/internat/MessagesBundle.properties
uis/src/com/biglybt/ui/swt/shells/GCStringPrinter.java

I tried the exercise of removing the constant value "BiglyBT" from the message bundles.
This is a system wide constant anyhow and shouldn't be translated into something different.
What I discovered was that this value could only be used for expansion and not on itself. 
This improvement introduces some default keys wich are expandable (like the others).
I am treating the wiki URLs are the same for all languages, at least that's how it currently is.  
If it were to be updated, then one had to call the method `updateProductName()`
Unit-tests are added for this change.

l10n constants

---

core/src/com/biglybt/core/metasearch/impl/DateParserRegex.java

I'm creating this PR as a test and a place for discussion.
I ran a search for CRLF line encodings and it trew me an error searching trough the files. 
The tool used pointed out that [this file](https://raw.githubusercontent.com/BiglySoftware/BiglyBT/master/core/src/com/biglybt/core/metasearch/impl/DateParserRegex.java) had some illegal characters for the windows codepage. 
If so then that's true for the ISO-8859-1 as they are fairly similar..
There are several interesting aspects to this. One is that github works great with UTF8... :)

Codebase encoding

---

core/src/com/biglybt/core/disk/impl/DiskManagerImpl.java
core/src/com/biglybt/core/helpers/TorrentFolderWatcher.java

Running an inspection found two cases of duplicate if conditions.

code cleanup: removed duplicate if-conditions

---

README.md

Spell it like that, you'll make Goolge mad!

README.md: It's never spelled "andriod"

---

core/src/com/biglybt/core/config/impl/ConfigurationChecker.java
core/src/com/biglybt/core/config/impl/ConfigurationDefaults.java
core/src/com/biglybt/core/networkmanager/VirtualChannelSelector.java
core/src/com/biglybt/core/networkmanager/impl/tcp/SelectorGuard.java
core/src/com/biglybt/core/networkmanager/impl/tcp/VirtualChannelSelectorImpl.java

The "safe selector mode" was a workaround for Java 1.4/1.5 under Windows.
When this particular workaround detected a spin, then and only then the property `"network.tcp.enable_safe_selector_mode"` would be set to `true`.
The above property was reset to `false` after a start/restart when the combo (operating system + java version) was different then for this workaround.
I'm leaving this as a work in progres (wip) for discussion.

Code cleanup: removed relic SelectorGuard handling

---

.editorconfig
core/src/com/biglybt/core/download/.editorconfig
core/src/com/biglybt/core/tag/.editorconfig
core/src/com/biglybt/core/tracker/.editorconfig
core/src/com/biglybt/core/util/.editorconfig
core/src/com/biglybt/pif/messaging/generic/.editorconfig
core/src/com/biglybt/pif/ui/components/.editorconfig
core/src/com/biglybt/pifimpl/local/ui/components/.editorconfig
core/src/com/biglybt/plugin/net/buddy/.editorconfig
core/src/org/json/jsonjava/.editorconfig

This commit installs a top-level `.editorconfig` file which attempts to incorporate, to the extent supported, the rules present in the `PreferencesJavaCodeStyleFormatter.xml` config and/or laid out in the `CODING_GUIDELINES.md` file.
Most rules are applied to `*.java` files only, although a few are applied for all files:
```
[*]
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```
Markdown files are also explicitly configured to 2-space indents.
Additionally, local `.editorconfigs` are installed at each level of the tree which contains existing `.java` files in CRLF line ending format, to explicitly preserve that format on those files only.
For example, `core/src/com/biglybt/core/util/.editorconfig` contains:
``` …
```

Add Editorconfig files

---

.gitignore

The master .gitignore was originally generated from GitHub's templates at https://github.com/github/gitignore but had fallen out of date. This syncs up with the changes there, and adds in the `Maven.gitignore` template as well.
The official `Java.gitignore` template excluded all packaged files, including .jar and .zip which the repo does contain (e.g. the SWT packages in `uis/lib/`), so I commented those out with a note.
Had no effect on the `git status` output in my local clone, but that's as it should be really.

Update gitignore from templates

---

core/pom.xml
uis/pom.xml

This will keep the `.editorconfig` files out of the packaged Jar:
```console
$ git co master
$ mvn package
[...]
$ jar tvf uis/target/BiglyBT.jar|grep -i editorconfig
56 Tue Jan 01 03:00:00 EST 1980 com/biglybt/core/download/.editorconfig
89 Tue Jan 01 03:00:00 EST 1980 com/biglybt/core/tag/.editorconfig
83 Tue Jan 01 03:00:00 EST 1980 com/biglybt/core/tracker/.editorconfig
116 Tue Jan 01 03:00:00 EST 1980 com/biglybt/core/util/.editorconfig
51 Tue Jan 01 03:00:00 EST 1980 com/biglybt/pif/messaging/generic/.editorconfig
35 Tue Jan 01 03:00:00 EST 1980 com/biglybt/pif/ui/components/.editorconfig
39 Tue Jan 01 03:00:00 EST 1980 com/biglybt/pifimpl/local/ui/components/.editorconfig
84 Tue Jan 01 03:00:00 EST 1980 com/biglybt/plugin/net/buddy/.editorconfig
35 Tue Jan 01 03:00:00 EST 1980 …
```

Exclude .editorconfig files from jar

---

.editorconfig
uis/.editorconfig

This configures `*.xml` for tab indents and 2-space tabs, but special-cases `uis/pom.xml` which is formatted with 4-space indents.

Add Editorconfig stanza for XML files

---

pom.xml

Running on the command line, Maven got complainey about the `<prerequisites>` for maven version in `pom.xml`, which are [no longer used](https://maven.apache.org/pom.html#Prerequisites) in Maven 3. Instead, the `maven-enforcer-plugin` provides the same functionality.
Before:
```console
$ mvn -N compile    
[INFO] Scanning for projects...
[WARNING] The project com.biglybt:biglybt-parent:pom:1.6.0.1-SNAPSHOT uses 
prerequisites which is only intended for maven-plugin projects but not for non 
maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. 
See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] 
[INFO] ---------------------< com.biglybt:biglybt-parent >---------------------
[INFO] Building BiglyBT - Parent 1.6.0.1-SNAPSHOT …
```

Use maven-enforcer instead of prerequisites

---

core/src/com/biglybt/platform/unix/startupScript

The startup script for Linux can be simplified by dropping the logic for running with GCJ. GCJ is limited to Java 5 and no longer able to run BiglyBT, and it has been removed from GCC 7 and is no longer shipped with recent Linux distributions.

Drop support for GCJ in the startup script

---

core/src/com/biglybt/core/security/CryptoECCUtils.java

Acording this commit [1]  Point compression was removed in bouncycastle, avoid use of removed API
[1]
https://src.fedoraproject.org/rpms/azureus/c/3f7722f761931b107a3d50721a24a702ed34f442?branch=f33

Port to latest bouncycastle API

---

core/src/com/biglybt/core/networkmanager/impl/tcp/TCPConnectionManager.java
core/src/com/biglybt/core/peer/impl/control/PEPeerControlImpl.java

(It's spelled correctly in `ICFG_NETWORK_MAX_SIMULTANEOUS_CONNECT_ATTEMPTS`, and the configuration path `network.max.simultaneous.connect.attempts`, but incorrectly in `TcpConnectionManager.{MIN,MAX}_SIMULTANIOUS_CONNECT_ATTEMPTS`.)

Correct spelling of "SIMULTANEOUS"

---

uis/src/com/biglybt/ui/swt/BlockedIpsWindow.java

In separate commits, this PR:
1. Adds code to automatically position the block log to the _bottom_ of its scroll, when the "Blocked IPs" window first opens. (The log is time-ordered, with the most recent entries at the bottom, so it makes sense to automatically make those items visible in the initial view.)
1. Trims a  whole bunch of trailing whitespace from the lines in that file. (My editor actually did that automatically, but I figured I'd submit it since I was opening a PR anyway. Like I said, it's a separate commit.)
I haven't actually tested this, myself — building a BiglyBT jar locally just requires way too much effort to test a one-line change. (Especially since I've upgraded to a newer Fedora release since the _last_ time I did that, and distro upgrades pretty reliably break my …

Blocked IP log initial scroll positioning

---

core/pom.xml

Building under JDK 1.8.0 / JDK 8, the `com.biglybt.core` classes can be compiled with the DNS SPI code in `...core.util.spi.AENameServiceDescriptor`. Thanks to the shim classes in `AENameServiceJava9.java` and `...Java12.java`, the compiled code can even be run under later JRE releases.
When building under JDK 9 or higher, `AENameServiceDescriptor.java` is uncompilable; the only option, [as @parg has noted](https://github.com/BiglySoftware/BiglyBT/issues/1017#issuecomment-873861491), is to "Just exclude the file from the build".
There's no reason that has to be a manual process, thanks to Maven's profiles feature. This PR adds a new profile, activated only when the Java version Maven is being run under is 9 or higher, that automatically excludes the `AENameServiceDescriptor.java` file …

Maven: Auto-exclude AENameServiceDescriptor based on JDK version

---

core/pom.xml

While attempting to make the inclusion of the `META-INF/services/` configuration file conditional, I moved it to a directory outside of the `META-INF` dir. That change was mostly inspired by [this example from the Maven docs](https://maven.apache.org/pom.html#resources), in the hope I could get away with including it by _default_, but still exclude it when a conditional profile is activated.
After that still didn't work, and I realized I'd have to have two profiles governing its inclusion/exclusion, the move became pointless. At that point I should've just put it back in its original location, to make the PR less disruptive to established tasks. I neglected to do that. My apologies.
Now that the file's restored to its original location, this PR updates the POM rules accordingly so that …

Maven: POM updates for services file location

---

.github/workflows/ci.yml
.travis.yml
core/pom.xml
pom.xml
uis/pom.xml

Now that the repo is trivially buildable using Maven under common JDK versions, this PR adds GitHub CI runs under JDK 8 and 11 on all three OS platforms.
Any build issues or outright failures in a job will cause it to fail. If it does _not_ fail, the final `BiglyBT.jar` file is published as a build artifact (actually, as 6 build artifacts) which can be retrieved from the job summary view under the Actions tab for any run.
The workflow is configured to run a CI job for all pushes to and pull requests targeting the `master` branch. It is also defined with a `workflow_dispatch` trigger, which means committers can manually trigger a run against any branch via the repo 'Actions' tab.
A JDK 17 build job is also defined, running on Ubuntu only, but currently allowed to fail because it _is_ …

GitHub Actions CI

---

core/pom.xml
core/src.test/com/biglybt/core/WikiTest.java
pom.xml

With this PR:
* The test method in the WikiTest class is converted to a JUnit `@ParameterizedTest`, and a new `ArgumentsProvider` class wraps the stream of wiki names/urls into a stream of test arguments. JUnit calls the test method once for each URL tested. (A single monolithic test becomes 43 separate, single-URL tests.)
* An `@Execution(ExecutionMode.CONCURRENT)` annotation is added to the test, allowing JUnit to execute instances in parallel.
* JUnit parallel execution is enabled in the POM, but turned off by default. (Meaning: only tests explicitly annotated for parallel execution will be run concurrently — currently, that's only the WikiTest instances.)
* The WikiTest is modified to remove all extraneous output, since tests can now be interleaved and unnecessary, incremental output …

Maven: Convert WikiTest to a ParameterizedTest, make concurrent

---

.github/workflows/ci.yml

GitHub has started browning out `macos-10.15`, as it's going away at the end of August.

CI: Switch to macos-latest

---

uis/src/com/biglybt/ui/swt/views/table/impl/TableRowSWTBase.java

`mustRefersh` => `mustRefresh`

Minor variable name spelling fix in TableRowSWTBase

---

uis/src/com/biglybt/ui/swt/columns/torrent/ColumnProgressETA.java

I noticed storms of these in my debug log earlier:
```text
[04:39:21] [stderr]   java.lang.NullPointerException
at com.biglybt.ui.swt.columns.torrent.ColumnProgressETA.cellPaint(ColumnProgressETA.java:486)
at com.biglybt.ui.swt.views.table.impl.FakeTableCell.invokeSWTPaintListeners(FakeTableCell.java:370)
at com.biglybt.ui.swt.views.table.impl.FakeTableCell.doPaint(FakeTableCell.java:1092)
at com.biglybt.ui.swt.views.table.impl.FakeTableCell.paintControl(FakeTableCell.java:1166)
at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5810)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
at …
```

ProgressETA: Avoid NPEs with FakeTableCell

---

core/src/com/biglybt/core/ipfilter/impl/IpFilterImpl.java

This PR consists of two commits which make minor/housekeeping changes to the logging in the IpFilter implementation:
1. Split up IPFilter LogIDs
- All filter-list management will still be logged to `LogIDs.CORE`. `CORE` is still the default `IpFilterImpl.LOGID`.
- Individual IP block activity will be logged to `LogIDs.NWMAN`, instead.
2. Lower block success logs to INFO
It never made sense to me, that the logs for blocked IPs were in the "core" logging stream, while everything else to do with connection setup and teardown was logged as "nwman". So, the first commit moves _only_ the logs for blocked-IP additions to "nwman", while leaving the logging for management of filter lists in the "core" stream.
It also never made sense to me that successful blocks (a perfectly normal …

IpFilter: Tweak logging

---

core/pom.xml
core/src/com/biglybt/core/global/GlobalManagerStats.java
core/src/com/biglybt/core/util/GeneralUtils.java
core/src/com/biglybt/ui/config/ConfigSectionStats.java
pom.xml
uis/pom.xml

This PR (in three separate commits)
1. Changes the configuration for smoothing window, by:
- Reducing the default `SMOOTHING_UPDATE_WINDOW` to `20`, down from `60`
- Reducing the _minimum_ value to `10`, down from `30`
- (Leaving the maximum value at `30 * 60`)
2. Removes an unused import from `core/src/com/biglybt/core/global/GlobalManagerStats.java`
3. Updates the build version in the pom files to `3.4.0.1-SNAPSHOT`
The current window values/constraints were arrived at many years ago, when speeds were much lower and swarms were much smaller. With modern broadband speeds and data rates, even a multi-gigabyte torrent might _complete_ downloading in under 60s, for many users.
When entire torrents download in a matter of seconds or single-digit minutes, because of the current 60s window the …

Shorten default smoothing window to 20s (min 10s)

---

core/pom.xml

fixes compilatione error: package sun.net.spi.nameservice does not exist on java 17

remove AENameServiceDescriptor from compilation for java 17
